### PR TITLE
Updated compatibility for Win32

### PR DESCRIPTION
**Pull request by DomAmato**
The parsing in vs2012 for windows moved everything over 1 so the new code tests for target system.
added defines for easy city setup and temperature unit during setup

### CODE REVIEW

**Comment by Hzikajr** [comment]
Sorry I didn't notice to your pull request... Thank you for your work anyway!!!!

**Comment by DomAmato** [comment]
no problem, I had the intention of adding a lot of cities but sorta forgot about it so maybe ill add some of those too

**Comment by DomAmato** [comment]
Ryo would you mind transfering ownership of this repo to me so that I can maintain it?

**Comment by Hzikajr** [comment]
Sure! I'm glad to hear from you. Thank you for your contribution on this repo!

**Pull request merged**
